services:
  postgres:
    image: postgres:16
    container_name: invoice-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: invoice
      POSTGRES_PASSWORD: invoice
      POSTGRES_DB: invoice
    ports:
      - '5432:5432'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U invoice -d invoice']
      interval: 5s
      timeout: 5s
      retries: 10
